### ISSUE TITLE
Which go version should be used?

### ISSUE THREAD

**Issue by Hoseong-Seo** [awslabs/eks-node-viewer#125]
Cloud9 has go1.18.x, It is not installed. 1.20.x is same.

**Comment by tzneal** [comment]
I just built it on cloud9 with 1.18 and it worked fine.  You can also just install a binary release:

```

wget https://github.com/awslabs/eks-node-viewer/releases/download/v0.3.0/eks-node-viewer_Linux_x86_64 -O eks-node-viewer
chmod a+x eks-node-viewer
./eks-node-viewer
``

**Comment by tzneal** [comment]
Feel free to re-open if you run into issues.
