### ISSUE TITLE
Build releases provising binary artefacts

### ISSUE THREAD

**Issue by mbevc1** [awslabs/eks-node-viewer#13]
To avoid people needing to build binaries and have the toolchaing installed locally, this repo should provide prebuild binary releases for major platforms via GH Releases.
i.e. https://goreleaser.com/

**Comment by mbevc1** [comment]
We probably want to add version info in the app as part of this work as well

**Comment by James-Quigley** [comment]
Would also be great if it were installable via `brew`!

**Comment by mbevc1** [comment]
For Golang binaries with GH releases I find this tool really useful ;) 

https://github.com/marcosnils/bin
