### ISSUE TITLE
support another resource type "pod-usages".

### ISSUE THREAD

**Issue by flavono123** [awslabs/eks-node-viewer#139]
using this tool when i migrate from the CAS to the Karpenter, sometimes i've watched that cpus or memories were available but more nodes created.

2 main reasons:

1 . the pod, would be scheduled, should be bounded in the specific AZ(since the PV).
2. the node had pods with the max # of pods of that.

imo, i have no idea to describe better for the first case. but the second case, **the num of pods, is good to describe as progression bars, like other resource types.**

both they are able to be checked with the label `topology.kubernetes.io/zone` and the computed label `eks-node-viewer/node-pods-usage`, but visual things would be better.

btw this tool is awesome. i really love this. thank you.

**Comment by tzneal** [comment]
Any resource name is visible as a progress bar, does this do what you want?


```
 eks-node-viewer --resources=pods,cpu,memory
```

**Comment by flavono123** [comment]
exactly, you always one step ahead from my thoughts :)

> 1 . the pod, would be scheduled, should be bounded in the specific AZ(since the PV).

what about this? any idea or plan on it?

**Comment by tzneal** [comment]
Sorry, I didn't follow that question. Can you explain further?

**Comment by flavono123** [comment]
ok. this is not the original question but let me explain
(i've already got [the answer](https://github.com/awslabs/eks-node-viewer/issues/139#issuecomment-1613598497) of the original one).

i'm raising a question **"is there a way to describe nodes' AZ as other resources?"**.

my thoughts:

- the AZ is similar with other resources.
  - when a new node come up with others' resources are "green"(e.g. cpu, memory, pods less then 50%)
  - but some pods should be scheduled in the AZ that others has not(e.g. others has only "-a", "-b", but "-c" one is required)
  - i guess there is a way to draw "graphical(or any how?)" AZs to indicate "resource sufficient" like others do with progress bars and colors.
- the AZ is not similar with others.
  - how could it possible to draw in a progress bar?
  
just very rough ideas.

**Comment by tzneal** [comment]
Sorry, I don't understand the request.

**Comment by flavono123** [comment]
Ok nevermind
