### ISSUE TITLE
color gradation reversal

### ISSUE THREAD

**Issue by thiru85** [awslabs/eks-node-viewer#141]
This is a great piece of software, thanks!

Could it be better if the visual aid's colors were reversed, meaning when the node is at 100% capacity, its red on the right vs on the left (which would be green). So at a glance, a user would know that if its red, the node is fully utilized.

**Comment by tzneal** [comment]
I picked the current color scheme so that low utilization (bad) was red and high utilization (good) was green.  I'm happy to accept a PR that leaves this as the default but has a command line option to swap it.
