### ISSUE TITLE
Feature: Add option to define profile name to fetch pricing information

### ISSUE THREAD

**Issue by nantiferov** [awslabs/eks-node-viewer#15]
Hello,

Very nice tool, thank you for open-sourcing it!

It seems to me that it's now tries to fetch pricing information with default profile credentials and if it's not defined, throws errors like: 
```log
2022/12/12 10:49:49 updating on-demand pricing, NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors; NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors, using existing pricing data from 2022-10-31T16:47:25Z
```

I think that it would be useful to have command line option to define custom profile in session init.

**Comment by spmason** [comment]
I've found that you can set the `AWS_PROFILE` environment variable as a workaround. I also need to set the `AWS_REGION` too or it also complains, eg:

```
AWS_PROFILE=<my_profile> AWS_REGION=eu-west-1 eks-node-viewer
```

**Comment by vumdao** [comment]
Nice tool but not much options such as `--profile` :)
