### ISSUE TITLE
Feature: change sort column

### ISSUE THREAD

**Issue by johnjeffers** [awslabs/eks-node-viewer#167]
It appears that eks-node-viewer currently sorts by node creation time, with oldest on top. Of all the options to sort by, creation time is probably the least interesting to me.

It would be very helpful to be able to choose other columns to sort by, and whether they are asc/desc, including arbitrary columns like the ones generated by `--extra-labels`. I label my nodes so I can see at a glance what provisioner they belong to, and being able to sort on the label column would be a huge help.

**Comment by kj187** [comment]
This is a great idea.. it would be great to have custom sorting. Sort by some extra-labels (string sort) or sort by memory/cpu
