### ISSUE TITLE
Not getting pricing info for spot instances and non-karpenter provisioned nodes

### ISSUE THREAD

**Issue by ronberna** [awslabs/eks-node-viewer#176]
Hello,

Initially I was getting pricing info for both spot and on-demand capacity for Karpenter provisioned nodes.  Was not getting capacity or pricing for other nodes in my cluster that were not provisioned by Karpenter.  Now, I'm only getting pricing info for on-demand capacity nodes provisioned by Karpenter. Does eks-node-viewer not show pricing and capacity for non-karpenter provisioned nodes?  Any idea why I'm not getting pricing for spot capacity Karpenter provisioned nodes?

![eks_node_viewer](https://github.com/awslabs/eks-node-viewer/assets/19379427/4f7b8dc5-0a6d-4c20-8168-c1342d2b619d)

eks-node-viewer version 0.4.3
commit: 23ccb3ad81bda06247c669a32f176b295d731290
built at: 2023-08-07T15:16:40Z
built by: goreleaser

**Comment by tzneal** [comment]
Where you are running it, do you have AWS creds so it can pull pricing information?

**Comment by ronberna** [comment]
Yes, I do have creds to get pricing info.  Tried it again today, and now looks like I'm getting pricing info for spot, but I'm not getting the pricing and capacity info for nodes not provisioned by Karpenter.  Is this by design or should the tool get all pricing and capacity info?

![eks-node-viewer-2](https://github.com/awslabs/eks-node-viewer/assets/19379427/0ccbdee2-2d1e-4dfa-80f9-f4c9932cd65c)

**Comment by tzneal** [comment]
What are all of the labels on one of those nodes?

**Comment by ronberna** [comment]
Here are the labels.  So nodes must have specific labels for eks-node-viewer to display this info?
![eks-node-viewer-3](https://github.com/awslabs/eks-node-viewer/assets/19379427/4efd0bf7-955f-455c-8e35-b1493c0c8438)

**Comment by tzneal** [comment]
Yes, we need to know if its an on-demand/spot/fargate node.  See https://github.com/awslabs/eks-node-viewer/blob/23ccb3ad81bda06247c669a32f176b295d731290/pkg/model/node.go#L53

**Comment by tzneal** [comment]
However you're initializing kubelet you'll need to pass in extra `--node-labels`. Once the labels are there, we'll display prices.

**Comment by ronberna** [comment]
Got it.  Looks like we're using --kubelet-extra-args in the launch template.  Problem though, the value needs to be set to either SPOT or ON_DEMAND.  If there is a spot and on-demand allocation strategy, what value does that eks.amazonaws.com/capacityType  get?
