### ISSUE TITLE
Scrollable UI

### ISSUE THREAD

**Issue by LolloneS** [awslabs/eks-node-viewer#177]
In big clusters (100+ nodes), I find myself not able to see all the nodes even though I keep my terminal's font size to the bare minimum I need to be able to read. If I try to scroll the UI, `eks-node-viewer` gets terminated. It would be great to have a way to scroll through the UI.

**Comment by tzneal** [comment]
It's scrollable with the left/right arrow keys as of version v0.4.0. Is that not working for you?

**Comment by LolloneS** [comment]
It works, thank you! Couldn't find it documented and I was running 0.3.x. Maybe it's worth adding it to the README/help?

**Comment by tzneal** [comment]
Sounds good!
