### ISSUE TITLE
Feature: Exposing data as Prometheus metrics

### ISSUE THREAD

**Issue by nthienan** [awslabs/eks-node-viewer#20]
It'd be great to expose data as Prometheus metrics. So that we can have better visualization and/or alerts

**Comment by tzneal** [comment]
I'm not sure what the request is for, this is a console tool for looking at node utilization.

**Comment by SoulKyu** [comment]
Create an image that could expose tools information as metrics on an endpoint so we could grab them through prometheus and expose them on Granfana could be a very good thing.

As you already have the data, it "only" about exposing it as a metrics

**Comment by nthienan** [comment]
@pete911  I want to run it as a pod inside the cluster

**Comment by pete911** [comment]
@nthienan, ok cool, I'll have a look what can be done and will let you know

**Comment by tzneal** [comment]
I'm going to close this one.  I want to keep the feature set of the viewer small. There are already metrics tools for reporting on pods/containers and this is intended to be an interactive CLI.
