### ISSUE TITLE
Tools seems to not use ENV KUBECONFIG for cluster information

### ISSUE THREAD

**Issue by SoulKyu** [awslabs/eks-node-viewer#22]
I'm overwriding my kubeconfig path with env var KUBECONFIG but this one is no't used when use eks-node-viewer.

So i have to perform this : cat ~/.kube/k0s.cfg > ~/.kube/config everytime i use eks-node-viewer on a different context (as my context is defined in another file path than the default one)

KUBECONFIG=/home/xxxxxx/.kube/k0s.cfg

**Comment by rothgar** [comment]
This support was added in #12 Please pull the latest code and rebuild.

**Comment by tzneal** [comment]
This should work now thanks to @rothgar , feel free to re-open if you still have issues.
