### ISSUE TITLE
Unable to install on cloud9 AL2 or AL2023

### ISSUE THREAD

**Issue by phsmiths** [awslabs/eks-node-viewer#258]
go install github.com/awslabs/eks-node-viewer/cmd/eks-node-viewer@latest
go: github.com/awslabs/eks-node-viewer/cmd/eks-node-viewer@latest (in github.com/awslabs/eks-node-viewer@v0.6.0): go.mod:5: unknown directive: toolchain

**Comment by tzneal** [comment]
You'll need to install a newer version of Go (at least v1.21) to build the tool.  Alternatively you can download a binary release from https://github.com/awslabs/eks-node-viewer/releases or install with brew as documented at https://github.com/awslabs/eks-node-viewer#homebrew.
