### ISSUE TITLE
got error

### ISSUE THREAD

**Issue by minkbear** [awslabs/eks-node-viewer#262]
I curl file (https://github.com/awslabs/eks-node-viewer/releases/download/v0.6.0/eks-node-viewer_Darwin_all) and run then got error `malformed Mach-o file: ./eks-node-viewer`

how can I solve this?

**Comment by tzneal** [comment]
What type of Mac do you have?

**Comment by minkbear** [comment]
> What type of Mac do you have?

@tzneal  MacOS Monterey version 12.6 on Intel processor

**Comment by minkbear** [comment]
tested with version 0.7.0 It's work.
