### ISSUE TITLE
Viewer only showing one node

### ISSUE THREAD

**Issue by smasset-orange** [awslabs/eks-node-viewer#297]
Thanks for the great tool.

I've noticed a weird bug when using it with unmanaged K8S clusters (obviously with pricing disabled as these actually run outside of AWS) and it seems it might be related to the fact the cluster has control plane nodes or not.

Here's a screenshot when running `eks-node-viewer -disable-pricing` on a vanilla K8S cluster with only 3 control plane nodes : 
![image](https://github.com/awslabs/eks-node-viewer/assets/86793256/610021ce-ebb1-4bcd-af68-edc88fcf11e1)

The node beeing displayed actually rotates between the 3 control plane nodes when the view is automatically refreshed.

Here's another screenshot running the same command on a non EKS managed cluster (without control plane nodes) :
![image](https://github.com/awslabs/eks-node-viewer/assets/86793256/8dbac06d-94a5-4e46-b672-226ad5bb3a42)

I've also tried to run it against a cluster with both control plane and compute nodes with a node selector filtering out the control plane which also resulted in the viewer only displaying one node at a time.

I've tested it against the `v0.5.0` and `v0.6.0` released versions and both showed the same results.

I know this is probably a corner case but do you think you can still look into it ?

Thanks for your help.

**Comment by tzneal** [comment]
The nodes are probably missing a providerID, which we expect to exist.

**Comment by smasset-orange** [comment]
(sorry for the delay, I just got back from vacation).

That was it ! I've assigned a different `.spec.providerID` for each node and now get the expected output.
Thanks.
