### ISSUE TITLE
Long name

### ISSUE THREAD

**Issue by NinoSkopac** [awslabs/eks-node-viewer#300]
I always struggle to remember the name of this tool.

How about `keks`

**Comment by tzneal** [comment]
We likely won't be changing the name.

**Comment by eden881** [comment]
You can add an alias to your `.zprofile` or `.bash_profile` to call it however you like:
```
alias keks='eks-node-viewer'
```

**Comment by NinoSkopac** [comment]
I know i know, i was just _trying_ to be cool or something
