### ISSUE TITLE
bug: Release v.0.7.0 is missing assets

### ISSUE THREAD

**Issue by mbevc1** [awslabs/eks-node-viewer#321]
Latest release only contains source, but not binary assets. Probably related to goreleaser config? :thinking:

**Comment by tzneal** [comment]
Yeah, goreleaser failed due to outdated config. Should hopefully be fixed with a 0.7.1 soon.

**Comment by tzneal** [comment]
I just deleted the v0.7.0 tag and recreated it after the fix, the artifacts are there now.

**Comment by mbevc1** [comment]
Cool, thanks :+1:
