### ISSUE TITLE
new on-demand instances show the spot price (on managed 1.21 node groups)

### ISSUE THREAD

**Issue by dekarl** [awslabs/eks-node-viewer#36]
While watching a node-group update of a managed EKS 1.21 node group I noticed that new instances come up as spot instances with the correct spot price and switch to on-demand after half a minute (when the capacityType label get's added) but keep showing the cached spot price instead of the correct on-demand price.

I'm not sure if the node should keep an attribute "last capacityType" and remove the cached price when lastCapacityType != currentCapacityType as that's a corner case.

The easiest solution might be to just not cache the price of a node at all and look it up for every update from the cached instance price lists. Or Update it, when updating a node?
https://github.com/awslabs/eks-node-viewer/blob/main/cmd/eks-node-viewer/main.go#L150

This was running version 164e1c984bbe12492a6cc21417dbd651f966de06

**Comment by kappa8219** [comment]
+1 with all nodes as spots. Even more after some time it just quits(with zero exit code). EKS 1.21.

-disable-pricing changes nothing.

**Comment by tzneal** [comment]
Should be resolved now, feel free to re-open if you still run into this.

**Comment by dekarl** [comment]
I just tested it with the latest version and its resolved in the sense that it doesn't show the wrong price anymore.

Instead fresh instances get shown without price and without capacityType. Once the capacityType is known only that is shown. The price remains NaN / empty.
