### ISSUE TITLE
Understand how eks-node-viewer obtain the metrics

### ISSUE THREAD

**Issue by dalvarezquiroga** [awslabs/eks-node-viewer#38]
Hello,

First of all , thanks to share this tool with community :-)

This is not an issue it's only a question, because I tested with a EKS cluster running inside AWS and the results don't match with others tool like top, htop etc....

![imagen](https://user-images.githubusercontent.com/20278092/207904169-6eca3f2f-83fa-4b15-9384-db87d3b19dc5.png)

As you can see in the screenshot I understand that the pods are using a lot of CPU but in other hand I can see that we are not using a lot of memory. 

In the next screenshot we can see the result of HTOP command.
![imagen](https://user-images.githubusercontent.com/20278092/207904874-f4ccfeba-a1bc-42fd-bf7d-8fac99e8a65d.png)

Here the result it's totally true compared with eks-node-viewer info, the memory is very low comparing with the total. --> 6.63GB of 30.9GB

But as you can see the CPU is not very high... for me is strange because in eks-node-viewer it said that is around 94%...

Here other screenshot about kubectl top nodes. 

![imagen](https://user-images.githubusercontent.com/20278092/207906262-27218fd7-d478-4e3e-bb8f-298ef6589351.png)

Maybe eks-node-viewer check the CPU sum for deployments?¿ Only take the limits? Because is reserved to the pods?¿ 

![imagen](https://user-images.githubusercontent.com/20278092/207907410-bcf751fe-797f-4dce-ba17-e0a85728a5ce.png)

Please would be possible to explain a little bit how to interpreter the results?

Thanks!! :-)

**Comment by tirelibirefe** [comment]
I checked eks-node-viewer too. The values are not correct.

**Comment by tzneal** [comment]
I commented above, but the eks-node-viewer shows the pod requests only. It doesn't look at the actual resources used by the pods.
