### ISSUE TITLE
Count of pods include pods in "Completed"state

### ISSUE THREAD

**Issue by khageshsaini** [awslabs/eks-node-viewer#40]
eks-node-viewer does an amazing job at displaying the resource allocation across nodes. The total no of pods shown on the right of cpu percentage includes the pods in **_non-running_** state which doesn't reflect the current resource allocation. Not sure if this is intended.

<img width="1351" alt="Screenshot 2022-12-18 at 8 42 33 PM" src="https://user-images.githubusercontent.com/5097988/208306117-5a5c4629-0871-4d41-8367-d46a6d6ac9e4.png">

<img width="1527" alt="Screenshot 2022-12-18 at 8 45 00 PM" src="https://user-images.githubusercontent.com/5097988/208306131-8a6b0f85-edfe-4634-af8b-cc1f6e4bb78b.png">

**The node shown above shows incorrect resources allocation.**

**Comment by kj187** [comment]
Its not only the count of pods, also the resources (cpu and memory) of the completed jobs are included in the visualization

**Comment by kj187** [comment]
Created a PR https://github.com/awslabs/eks-node-viewer/pull/49
