### ISSUE TITLE
bars dont refresh

### ISSUE THREAD

**Issue by FernandoMiguel** [awslabs/eks-node-viewer#51]
i had ENV running in a shell, and spun up 20 new pods/nodes and the CLI app updated to include the new nodes but not the stats about them
![image](https://user-images.githubusercontent.com/168366/209353011-62477932-21db-4b89-b192-1befab0eef98.png)

after I restarted the app all the expected details where there 
![image](https://user-images.githubusercontent.com/168366/209353173-cf1d0be4-c063-417a-b0ba-1b415b10fbf0.png)

**Comment by ikohlernz** [comment]
+1 same behavior on AWS Cloud9 instance the bars do not refresh properly and I have quite and start again to see the new status.

**Comment by tzneal** [comment]
I haven't been able to reproduce this, I even ran it on AWS CloudShell and it updated when pod/nodes changed.

**Comment by FernandoMiguel** [comment]
Mac OS ventura M1
Latest iterm2

There's a top up saying this is an interactive shell and if I want to let it refresh, I say yes, usually.

**Comment by ikohlernz** [comment]
Here is some screeenshot when new node is added and even after 2mins it does not show any pods on it only after quit and start again.
![new_node_eks_viewer](https://user-images.githubusercontent.com/60406185/210640911-03452386-fbed-415b-9aae-4fe4acd38aec.png)
Workernode added ^^
![new_node_eks_viewer-2](https://user-images.githubusercontent.com/60406185/210640943-2ffda71d-9183-4b0b-9ef1-4ae511567e41.png)
Workernode up for 2mins, so should be in ready state by now but timer still going ^^
![new_node_eks_viewer-3](https://user-images.githubusercontent.com/60406185/210640955-1eabbd24-0092-44b5-8d6d-4c020d749420.png)
After quit and start again it all looks fine ^^

Here is an example when running 2 session one is up before the node comes online fully:
![eks-viewer-not](https://user-images.githubusercontent.com/60406185/210641925-25a5d569-0061-47b6-b717-d9309a9febb2.png)
And this is another session in new shell started about 30 seconds after the new node is provisioned.
![eksviewer-ok](https://user-images.githubusercontent.com/60406185/210642105-f9e85396-d1f0-41d9-aaae-2917cc77cb91.png)


AWS Cloud9 using ami "amazon/Cloud9AmazonLinux2-2022-08-01T09-18".  Happy to supply more info.

**Comment by mbevc1** [comment]
Same here on Linux Fedora 37. Starts refreshing and stops after a short period
