### ISSUE TITLE
Feature Request: Authenticate Using built-in IAM role from the ec2 machine 

### ISSUE THREAD

**Issue by yashtandon019** [awslabs/eks-node-viewer#74]
Currently to use the utility we can only use the `~/aws/credentials ` or the aws config, but is it also possible to use the built-in IAM role in the machine ?

**Comment by bwagner5** [comment]
It should work on EC2. I just tested it on an EC2 instance with an IAM instance profile attached. The only thing I needed to set is the AWS_REGION environment variable:

```
> aws eks update-kubeconfig --name my-cluster
> ## Updated the aws-auth config map to my instance role access to the cluster

> curl -fsSL https://github.com/awslabs/eks-node-viewer/releases/download/v0.3.0/eks-node-viewer_Linux_x86_64 > eks-node-viewer

> AWS_REGION=us-east-2 eks-node-viewer
```

**Comment by tzneal** [comment]
Closing since this should be resolved now, feel free to re-open if you run into issues.
