### ISSUE TITLE
NoCredentialProviders error when using SSO credentials

### ISSUE THREAD

**Issue by iandelahorne** [awslabs/eks-node-viewer#78]
When using eks-node-viewer with credentials provided from AWS SSO, I'm seeing:
```
2023/02/16 16:07:40 updating on-demand pricing, NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors; NoCredentialProviders: no valid providers in chain. Deprecated.
```
Setting `AWS_PROFILE` does not solve the issue.

Looking at issues in aws-sdk-go, this seems to be related to aws-sdk-go v1 not playing well with SSO. It might be fixed in v2?

**Comment by tzneal** [comment]
Does setting `export AWS_SDK_LOAD_CONFIG=true` solve this for you?

**Comment by iandelahorne** [comment]
@tzneal It does fix it! Is there a way to make this a default in the tool?

**Comment by tzneal** [comment]
I don't think it really should be, it's common across the AWS SDKs that you set AWS_SDK_LOAD_CONFIG to cause it to load an SDK file.  You can always add it to your .bashrc/.zshrc.

**Comment by iandelahorne** [comment]
@tzneal I'm sorry but all other tools that access via SSO, like aws-iam-authenticator et c don't need this setting. If it's common it's the first I've come across while using SSO auth over the last 3+ years.
