### ISSUE TITLE
Installation of latest v0.1.1 release is failing

### ISSUE THREAD

**Issue by itselavia** [awslabs/eks-node-viewer#84]
I'm following the Autoscaling section in the [EKS Immersion Workshop](https://catalog.workshops.aws/eks-immersionday/en-US/autoscaling) \
The command to install eks-node-viewer is:
`go install github.com/awslabs/eks-node-viewer/cmd/eks-node-viewer@latest`
That fails with:
`../../go/pkg/mod/github.com/awslabs/eks-node-viewer@v0.1.1/cmd/eks-node-viewer/main.go:44:12: pattern ATTRIBUTION.md: no matching files found`

I edited the command to install the v0.1.0 version and that worked:
`go install github.com/awslabs/eks-node-viewer/cmd/eks-node-viewer@v0.1.0`

**Comment by tzneal** [comment]
You can download binaries directly from https://github.com/awslabs/eks-node-viewer/releases, but I'll also fix it so go install latest works.

**Comment by tzneal** [comment]
Fixed now:

```
$ go install github.com/awslabs/eks-node-viewer/cmd/eks-node-viewer@latest
go: downloading github.com/awslabs/eks-node-viewer v0.1.2
```
