### ISSUE TITLE
Pricing not showing up and bars not refreshing

### ISSUE THREAD

**Issue by mudasirmirza** [awslabs/eks-node-viewer#89]
As shown in the screenshot below, pricing is not showing up. Also the bars are not refreshing. It seems like it's just stuck.

```
eks-node-viewer version 0.1.3
commit: 868b27101807da01031c47cc467d5d8a8a0d62b4
built at: 2023-02-25T00:02:55Z
built by: goreleaser
```

<img width="999" alt="Screenshot 2023-03-03 at 6 16 09 PM" src="https://user-images.githubusercontent.com/1905439/222743117-ed8508f6-dec1-484b-8882-aae0d68a01d5.png">

**Comment by tzneal** [comment]
Are any error messages printed to the screen when you run it?

**Comment by tzneal** [comment]
I recently fixed a spot pricing issue, please re-open if you are still seeing issues.

**Comment by mudasirmirza** [comment]
Hi @tzneal ,

This is still not showing price data, also still if I run without exporting the ENV vars, I still get the errors

```
2023/03/25 17:04:59 updating fargate pricing, NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
2023/03/25 17:04:59 updating on-demand pricing, NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors; NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors, using existing pricing data from 2022-12-05T13:09:08Z
```

End even me exporting env var, still no price data

```
export AWS_SDK_LOAD_CONFIG=true
export AWS_REGION=ap-south-1
export AWS_PROFILE=eks-prod
```

**Comment by clay-risser** [comment]
I'm not seeing price data either.

**Comment by ronberna** [comment]
I'm also not seeing pricing data.  Before I was getting pricing data for both spot and on-demand karpenter provisioned nodes.  I'm not getting pricing or capacity type for non-karpenter provisioned nodes.  Now I'm only getting pricing data for on-demand karpenter provisioned nodes and nothing for spot.  Does eks-node-viewer only show pricing and capacity for karpenter provisioned nodes or should I get this data for both karpenter and non-karpenter provisioned nodes?

**Comment by mudasirmirza** [comment]
Hi,

Did anyone figure out why pricing data is not showing up. This is still happening with me, tried multiple accounts, multiple regions and multiple clusters still the same.

No idea why pricing data is not showing and no errors or messages on the screen.

**Comment by ronberna** [comment]
I was not getting any pricing data for non-karpenter provisioned nodes.  The reason for this is because eks-node-viewer is looking for a **capacity-type** label on the node so that it knows the pricing data to look up.  Besides making sure your region is set, you should check if the nodes that are not showing pricing info have a **capacity-type** label.  In my case, I had to add logic to the ASG Launch Template user data to set the **capacity-type** label when a node is created.
