### ISSUE TITLE
Installation doesn't seems to work

### ISSUE THREAD

**Issue by orojina** [awslabs/eks-node-viewer#9]
Hello, first of all thanks for the tool, it looks great.

The problem I'm facing is that even when I followed the instructions from the README to install the eks-node-viewer cli,  after the installation the command is not available.

![image](https://user-images.githubusercontent.com/11845190/206747381-c3312f61-bcf9-409d-aa83-e2834d177162.png)
![image](https://user-images.githubusercontent.com/11845190/206747512-767fec75-92f6-427d-91c1-db2dd856ec7f.png)

```
❯ go version
go version go1.19.4 darwin/amd64
```

I had to clone the repo and build it locally to make it work:
![image](https://user-images.githubusercontent.com/11845190/206747816-daefd8b2-def5-4df7-91c1-311a663d8d50.png)

**Comment by ellistarn** [comment]
You need to add your go bin to your path. Mine is 
```
export PATH=$PATH:/Users/etarn/workspaces/go/bin
```

**Comment by dushyant8858** [comment]
It worked for me, thank you for sharing :)

**Comment by orojina** [comment]
Yes that worked, thanks @ellistarn 👍🏻
